version: '3.2'

services:
  sportsonline:
    image: "sportsonline:v1"
    tty: true
    ports:
      - "1000:3000"
    environment:
      PATH: "/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      TZ: "Africa/Luanda"
    build: .
    # ======== Windows
    #volumes:
      #- "~/sportsonline/:/sportsonline/"
    # ====== Linux && MacOS
    volumes:
      - "./sportsonline/:/sportsonline/"
    networks:
      - frontend
      - backend

# mongood - Exemplo de como interligar a base de dados a aplicação
# Ilustrativo e somente um exemplar 
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb_sportsonline
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: myadminpassword
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

# Interligação entre frontend App com a base de dados
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
