version: '3.2'

services:
  sportsonline:
    image: "sportsonline:v1"
    tty: true
    ports:
      - "3000:3000"
    environment:
      PATH: "/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      TZ: "Africa/Luanda"
    build: .
    depends_on:
      - db
  db: 
    image: 'postgres:latest' 
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: sportsonline_development


